
- name: Download zabbix repo package
  get_url:
    url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb
    dest: /tmp/zabbix.deb
    validate_certs: false
  tags: zabbix-agent

- name: Install zabbix repo
  become: yes
  apt:
    deb: /tmp/zabbix.deb
    state: present
  ignore_errors: true   
  tags: zabbix-agent

- name: --- apt update ---
  shell: apt update
  ignore_errors: true
  tags: zabbix-agent

- name: --- Install zabbix agent ---
  apt:
    name: ['{{agent}}', zabbix-agent2-plugin-mongodb, zabbix-agent2-plugin-postgresql]
    state: present
  tags: zabbix-agent

- name: --- zabbix gaent config ---
  template: 
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
  tags: zabbix-agent 

- name: --- restart zabbix service ---
  service:
    name: zabbix-agent2
    state: restarted
  tags: zabbix-agent
